apiVersion: v1
kind: Pod
metadata:
  name: todo-app
spec:
  containers:
    - name: database
      image: localhost/database
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: myp455
        - name: MYSQL_DATABASE
          value: tareas
    - name: backend
      image: localhost/backend
      env:
        - name: APP_SETTINGS
          value: project.DevelopmentConfig
        - name: API_KEY
          value: test
        - name: DATABASE_URL
          value: 'mysql+pymysql://root:myp455@localhost/tareas'
        - name: DATABASE_HOST
          value: localhost
    - name: frontend
      image: localhost/frontend
      env:
        - name: BACKEND_HOST
          value: "localhost:8080"
        - name: API_KEY
          value: test
      ports:
        - name: 80/TCP
          containerPort: 80
          hostPort: 8080
          protocol: tcp
